// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1PK9aUxf1hiF3TO0p3K8lJ_ESitbVf1Q',
    appId: '1:550855070952:web:018b09baab88e844f6a55d',
    messagingSenderId: '550855070952',
    projectId: 'flutterapp-4e8ed',
    authDomain: 'flutterapp-4e8ed.firebaseapp.com',
    storageBucket: 'flutterapp-4e8ed.appspot.com',
    measurementId: 'G-M3VTX1R3VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0jFQP_-JqdIKWANHLyPCp_EVP5xoaaQ',
    appId: '1:550855070952:android:c39d45236345f8cff6a55d',
    messagingSenderId: '550855070952',
    projectId: 'flutterapp-4e8ed',
    storageBucket: 'flutterapp-4e8ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtU6BXZuwnL1ErisxPQgYRcykf4SMs210',
    appId: '1:550855070952:ios:72d783649170f023f6a55d',
    messagingSenderId: '550855070952',
    projectId: 'flutterapp-4e8ed',
    storageBucket: 'flutterapp-4e8ed.appspot.com',
    iosBundleId: 'com.example.firebaseConnection',
  );
}
